### ISSUE TITLE
Improve horizontal scroll visibility in app-db inspectors

### ISSUE THREAD

**Issue by hipitihop** [Day8/re-frame-trace#146]
I notice individual horizontal scroll bar on each app-db inspector, but there is also an overall vertical scroll bar for the whole tab. Frequently the horizontal scrollbar is off screen. I initially thought there was none. Is it possible to put a single overall horizontal one on the tab which would always be visible ?

![image](https://user-images.githubusercontent.com/4626024/35953528-cf598b16-0cd0-11e8-8d84-4287849fdaea.png)

**Comment by danielcompton** [comment]
I think the current behaviour is probably still a better option than putting a single horizontal scroll bar on the whole panel. It would make rendering look a bit ugly because data would be rendered out over the right edge of the pods, and it makes it hard to view multiple paths at once if one is way out the right hand side.

We want to be encouraging people to be scoping in to app-db as well. Best case scenario, this will be fixed in https://github.com/Day8/re-frame-trace/issues/123.

**Comment by hipitihop** [comment]
Agree. #123 and possibly some scoping shortcuts in the UI will help
