### ISSUE TITLE
Epochs

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-trace#2]
Epochs are defined as being the bounds between an event being fired, and all subsequent events, db updates, subscriptions, and renders being run. This is inherently a little bit of a fuzzy concept, as there may be events added to the re-frame event queue by async network activity which becomes part of the epoch, even though it is logically separate. For developing and debugging purposes to show the separation of events this is good enough.

How do we know when we are in a new epoch? How do we know when it is finished? Just based on events? Should there be something fired at the end of the render?

We also want to show in the trace view the bounds of each epoch.

**Comment by daiyi** [comment]
I am really interested in tackling this issue, because surfacing the most important information and collapsing everything else would really change the whole debugging experience. 

Is there some people who might be familiar with the internals of re-frame that you could suggest I reach out to to have a discussion about this with?

**Comment by danielcompton** [comment]
Fixed in master with new epoch based view.
