### ISSUE TITLE
:input-signals is always nils?

### ISSUE THREAD

**Issue by Dexterminator** [Day8/re-frame-trace#83]
As far as I can see, the :input-signals key always has a nil value, regardless of the actual input signals. Unsure what the behaviour should actually be here.

![](https://puu.sh/xEHwL/197b8a4d33.png)

**Comment by danielcompton** [comment]
This is calculated at https://github.com/Day8/re-frame/blob/b7be7864a4d65b2eacafd18e4d9971490b8ddd37/src/re_frame/subs.cljc#L165-L173. The idea is to capture the input signals ID (same format as `:reaction`, i.e. "rx16"). This lets you track down which specific subscription is running, and catch when things aren't being disposed properly. It used to work, I'm not sure why it's not showing up here. Expected behaviour would be to get a list of input signals ids. I wonder if the CLJ version of `rf.interop/reagent-id` is being used here instead of the CLJS one?
